{{- range $name, $config := .Values }}
{{- if and $config.cm $config.cm.enabled $config.cm.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-config-{{ $name }}
  namespace: cronjob
data:
{{- range $k, $v := $config.cm.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
{{- end }}
{{- end }}