apiVersion: v1
kind: ConfigMap
metadata:
    namespace: wiki
    name: wiki-config-wiki-app
data:
   DB_TYPE: postgres
   DB_HOST: svc-postgres
   DB_PORT: "5432"
   DB_USER: wikijs
   DB_PASS: wikijsrocks
   DB_NAME: wiki

---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: wiki
    name: db-postgres-config
data:
   POSTGRES_DB: wiki
   POSTGRES_PASSWORD: wikijsrocks
   POSTGRES_USER: wikijs