secretspass-credentials:
    external_secret_name: secretspass-credentials
    namespaces:
      - secretpass
    refreshInterval: 30m
    secretStoreRefName: aws-secret-store
    target: secretspass-credentials
    dataFrom:
      extract:
        key: secretspass-credentials

external-dns-secrets:
    external_secret_name: external-dns-secrets
    namespaces:
      - external-dns
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target: aws-secret
    dataFrom:
      extract:
        key: route53-access

cronjob-fortigate:
    external_secret_name: cronjob-fortigate
    namespaces:
      - cronjob
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target: cronjob-credentials-fortigate-backup
    dataFrom:
      extract:
        key: BUCKET-CRONJOB

cronjob-juniper:
    external_secret_name: cronjob-juniper
    namespaces:
      - cronjob
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target: cronjob-credentials-juniper-backup
    dataFrom:
      extract:
        key: juniper-credentials

cert-manager-secrets:
    external_secret_name: cert-manager-secrets
    namespaces:
      - cert-manager
    refreshInterval: 1m
    secretStoreRefName: aws-secret-store
    target: aws-secret
    dataFrom:
      extract:
        key: route53-access

loki-credentials:
    external_secret_name: loki-credentials
    namespaces:
      - monitoring
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target:  aws-secret
    dataFrom:
      extract:
        key: keys

grafana-credentials:
    external_secret_name: grafana-credentials
    namespaces:
      - monitoring
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target:  aws-secret-grafana
    dataFrom:
      extract:
        key: secrets-grafana


grafana-secret-sso:
    external_secret_name: grafana-secret-sso
    namespaces:
      - monitoring
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target:  aws-secret-grafana-sso
    dataFrom:
      extract:
        key: secret-sso

secretpass-metrics-auth:
    external_secret_name: secretpass-metrics-auth
    namespaces:
      - monitoring
    refreshInterval: 168h
    secretStoreRefName: aws-secret-store
    target:  aws-secret-secretpass-metrics-auth
    dataFrom:
      extract:
        key: secretpass-metrics-auth