backup-fortigate:
  cronjob_name: backup-fortigate
  schedule: "*/1 * * * *" # every month at 00:30 "30 0 1 * *"
  image:
    name: shlomobarzili/fortigate
    tag: v1.2.1

  env:
    - name: USERNAME
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: USERNAME
    - name: PASSWORD
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: PASSWORD
    - name: AWS_ACCESS_KEY_ID
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: AWS_SECRET_ACCESS_KEY
    - name: HOST
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: HOST
    - name: BUCKET_NAME
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: BUCKET_NAME  
    - name: PORT
      secretName: cronjob-credentials-fortigate-backup
      key:
        name: PORT
  volumeMounts:    
      enabled: true
      pvc:
        name: cronjob-pvc-backup-fortigate
        accessModes: 
          - ReadWriteOnce
        mountPath: /app


  cm:
    enabled: true
    data:
      PUSHGATEWAY_ADDR: "prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
      PUSHGATEWAY_JOB: "backup-fortigate"
      PUSHGATEWAY_INSTANCE: "backup-fortigate"
      FW_NAME: "FW-Shlomi #"

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true    

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]      

backup-juniper:
  cronjob_name: backup-juniper
  schedule: "*/1 * * * *" # every month at 00:00 "0 0 1 * *"
  image:
    name: shlomobarzili/junipersw
    tag: v1.2.1

  env: 
    - name: USERNAME
      secretName: cronjob-credentials-juniper-backup
      key:
        name: USERNAME
    - name: PASSWORD
      secretName: cronjob-credentials-juniper-backup
      key:
        name: PASSWORD
    - name: AWS_ACCESS_KEY_ID
      secretName: cronjob-credentials-juniper-backup
      key:
        name: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      secretName: cronjob-credentials-juniper-backup
      key:
        name: AWS_SECRET_ACCESS_KEY
    - name: HOST
      secretName: cronjob-credentials-juniper-backup
      key:
        name: HOST
    - name: BUCKET_NAME
      secretName: cronjob-credentials-juniper-backup
      key:
        name: BUCKET_NAME    
    - name: PORT
      secretName: cronjob-credentials-juniper-backup
      key:
        name: PORT
  volumeMounts:    
      enabled: true
      pvc:
        name: cronjob-pvc-juniper
        accessModes: 
          - ReadWriteOnce
        mountPath: /app
  cm:
    enabled: true
    data:
      PUSHGATEWAY_ADDR: "prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
      PUSHGATEWAY_JOB: "backup-juniper"
      PUSHGATEWAY_INSTANCE: "backup-juniper"
      SW_NAME: "@Juniper_BB>"

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true    

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]      