reloader:
  watchGlobally: true
  namespaceSelector: "kubernetes.io/metadata.name in (secretpass,monitoring,cronjob)"
  deployment:
    replicas: 1
    revisionHistoryLimit: 0

  rbac:
    create: true
    serviceAccount:
      create: true
      name: reloader